In [1]:
import numpy as np
import pandas as pd

In [45]:
np.random.seed(42)

df=pd.DataFrame({ "ID":range(1,1001),"Gender":np.random.choice(["Male","Female"],size=1000,p=[0.7,0.3]
    ),
    "Marks":np.random.randint(40,100,1000)
})
df.describe()

                ID       Marks
count  1000.000000  1000.00000
mean    500.500000    69.50800
std     288.819436    17.27137
min       1.000000    40.00000
25%     250.750000    54.00000
50%     500.500000    69.00000
75%     750.250000    84.25000
max    1000.000000    99.00000

### Simple Random Sampling (SRS)
in this sampling every student have equal chance to be selected because we are selecting randomly

In [46]:
srs=df.sample(n=100,random_state=42)
srs.shape

(100, 3)

In [47]:
print(df["Marks"].mean())### original data
print(srs["Marks"].mean()) ###sample data from original

69.508
70.89

### Stratified sampling method
Making the groups before taking the sample data 
 then after creating the groups then selecting the sample data from the groups and combine them to use 
### These groups are called Strata

In [49]:
print(df["Gender"].value_counts())

Gender
Male      712
Female    288
Name: count, dtype: int64

In [51]:


male_data=df[df["Gender"]=="Male"].sample(n=50,random_state=45)
fem_data=df[df["Gender"]=="Female"].sample(n=50,random_state=45)

# Here we have created Two startas male_data and fem_data

# Now we are going to add both the data together to get the final sample data 

final_data=pd.concat([male_data,fem_data])

final_data.shape

(100, 3)

### Create a dataset of cricket players having given columns 
1-Total matches played
2-Centuries 
3-Half centuries 
4-Highest score 
5-Total runs 
6-Strike rate 

You need to find the mean of sample data and original data and find the diff of the mean in the simple data and original for each columns 

You have to perform both sampling methods SRS and SSM

## Conveninence Sampling

In [52]:
df_sort=df.sort_values(
    by="Marks",
    ascending=False
)
df_sort

      ID  Gender  Marks
599  600    Male     99
65    66    Male     99
659  660    Male     99
540  541  Female     99
709  710    Male     99
..   ...     ...    ...
755  756  Female     40
126  127  Female     40
908  909    Male     40
140  141  Female     40
915  916    Male     40

[1000 rows x 3 columns]

In [53]:
conv_samp=df_sort.head(100)
print(conv_samp["Marks"].mean())
print(df["Marks"].mean())

96.83
69.508

## Cluster Sampling

In [54]:
divisions=["A","B","C","D"]

df["Division"]=np.random.choice(divisions,1000)
df

       ID  Gender  Marks Division
0       1    Male     86        A
1       2  Female     51        C
2       3  Female     55        D
3       4    Male     63        C
4       5    Male     58        D
..    ...     ...    ...      ...
995   996    Male     87        D
996   997  Female     92        B
997   998    Male     91        A
998   999  Female     85        A
999  1000    Male     66        B

[1000 rows x 4 columns]

In [55]:
clust=np.random.choice(divisions,size=2)
print(clust)

clust_samp_data=df[df["Division"].isin(clust)]
clust_samp_data

['A' 'B']

       ID  Gender  Marks Division
0       1    Male     86        A
6       7    Male     70        B
8       9    Male     56        B
9      10  Female     62        B
10     11    Male     76        B
..    ...     ...    ...      ...
992   993    Male     73        B
996   997  Female     92        B
997   998    Male     91        A
998   999  Female     85        A
999  1000    Male     66        B

[508 rows x 4 columns]

In [44]:
len(clust_samp_data)

NameError: name 'clust_samp_data' is not defined